name: Build APK from HTML

on:
  push:
    branches: [ "main" ]   # Если ваша ветка называется master, замените main на master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Build APK from HTML
      uses: darkshredder/web-to-app-action@main
      with:
        build-folder-path: "."          # папка, где лежит index.html (корень)
        app-name: "RODA Remote"         # название приложения
        output-folder-path: "my-apks"   # папка для готового APK

    - name: Upload APK
      uses: actions/upload-artifact@v4
      with:
        name: RODA-Remote-APK
        path: my-apks/*.apk             # загружаем все APK из этой папки
